int getString(char* msg, char* msgError, int min, int max, int* reintentos, char* resultado);
int Utils_getChar(char* msg, char* msgError, int min, int max, int reintentos, char* resultado);
int isValidName(char* stringRecibido);
int Utils_getInt(  char* msg,char* msgError,int minSize,int maxSize,int min,int max,int reintentos,int* input);
int Utils_validaInt(char* stringRecibido);
int isValidSignedNumber(char* stringRecibido);
int Utils_getFloat(char* msg, char* msgError, int minSize, int maxSize, int min, int max, int reintentos, float* input);
int Utils_validaFloat(char* stringRecibido);
int Utils_getTelefono(char* msg, char* msgError, int minSize, int maxSize, int min, int max, int reintentos, char* input);
int isValidTelephone(char* stringRecibido);
int Utils_getDNI(char* msg, char* msgError, int minSize, int maxSize, int reintentos, char* input);
int isValidDNI(char* stringRecibido);
int Utils_getCUIT(char* msg, char* msgError, int reintentos, char* input);
int isValidCUIT(char* stringRecibido);
int Utils_getEmail(char* msg, char* msgError, int minSize, int maxSize, int reintentos, char* input);
int isValidEmail(char* stringRecibido);
int utn_getTexto(char* msg, char* msgError, int minSize, int maxSize, int reintentos, char* input);
int isValidTexto(char* stringRecibido);
int Utils_getAlfanumerico(char* msg, char* msgError, int minSize, int maxSize, int reintentos, char* input);
int isValidAlphanumeric(char* stringRecibido);
int Utils_getChar2(char* msg, char* msgError, int min, int max, int reintentos, char* resultado);
int isValidChar(char charRecibido);
